server:
  servlet:
    context-path: /iot-registry
spring:
  application:
    name: registry-service
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  datasource:
    url: some_url
    username: some_user
    password: some_password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: RegistryServiceHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  devtools:
    restart:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  ratelimiter:
    instances:
      get_device_limiter:
        limitForPeriod: 1000       # Max calls per period
        limitRefreshPeriod: 1s     # Period
        timeoutDuration: 0
  retry:
    instances:
      updateDeviceRetry:
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.dao.ConcurrencyFailureException
          - org.springframework.dao.TransientDataAccessException
          - java.sql.SQLTransientException
kafka:
  consumer:
    topic: iot-devices-data
    poll-timeout-ms: 2000
    properties:
      bootstrap-server: localhost:9092
      group.id: my-consumer-group
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
parallel-persister:
  threads-amount: 10
